### ISSUE TITLE
TypeError: dist must be a Distribution instance

### ISSUE THREAD

**Issue by dzyjjpy** [princeton-vl/pose-ae-train#45]
**pytorch:1.2.0, torchvision:0.4.0**
When I excute the comand: **python build.py install**
as errors occured(create_extension is deprecated), so I edit the code as below:
# from torch.utils.ffi import create_extension?
from torch.utils.cpp_extension import BuildExtension

extra_objects = ['src/my_lib_kernel.o']  **# there is no my_lib_kernel.o file in project subdirectory /src/** 
extra_objects = [os.path.join(this_file, fname) for fname in extra_objects]

# ffi = create_extension(
ffi = BuildExtension(
    '_ext.my_lib',
    headers=headers,
    sources=sources,
    define_macros=defines,
    relative_to=__file__,
    with_cuda=with_cuda,
    **extra_objects=extra_objects**  # **error happened this line**
)

TypeError happened as below:
Including CUDA code.
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    extra_objects=extra_objects
  File "/home/jiapy/virtualEnv/py3torch1.2/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 233, in __init__
    super(BuildExtension, self).__init__(*args, **kwargs)
  File "/home/jiapy/virtualEnv/py3torch1.2/lib/python3.6/site-packages/setuptools/__init__.py", line 163, in __init__
    _Command.__init__(self, dist)
  File "/usr/lib/python3.6/distutils/cmd.py", line 57, in __init__
    raise TypeError("dist must be a Distribution instance")
**TypeError: dist must be a Distribution instance**

Anyone have similar experience? Any advice for solving the issue will be appreciated. Thanks

**Comment by dzyjjpy** [comment]
try to downgrade setuptools's version to 20.0, it doesn't work...

**Comment by dzyjjpy** [comment]
Hi @anewell do you have any advice for the issue?

**Comment by zhangming8** [comment]
I meet the same problem, has anyone solved it ?

**Comment by wanfb** [comment]
my_lib_kernel.o is the output of the comment "os.system("cd src;nvcc my_lib_kernel.cu -c -o my_lib_kernel.o -x cu -Xcompiler -fPIC -arch=sm_52")"  in build.py. You can actually try to run this comment first.

**Comment by wanfb** [comment]
I finally solved this problem by downgrading pytorch version to 0.4.0 and using ubuntu version 16.04.

**Comment by leoluopy** [comment]
> I finally solved this problem by downgrading pytorch version to 0.4.0 and using ubuntu version 16.04.

thanks for sharing the method , i created a new torch env using pyenv ,and the problem is solved

**Comment by Boatsure** [comment]
same problem， downgrade setuptools to 0.9.8 solve this error, but it comes out other errors which need upgrade setuptools...
